### ISSUE TITLE
Using Html 5 approach: <!DOCTYPE html> results in vertically scrollbar on images

### ISSUE THREAD

**Issue by zsoerenm** [nyroDev/nyroModal#53]
I figured it out now:
Using Html 5 approach: <!DOCTYPE html> instead of Transistional Html 4 results in a vertically scrollbar on images in every Browser I tested: FF 3.6, Opera 11, IE 8

**Comment by Sade** [comment]
same problem with <b>Chrome 10</b>.

**Comment by phlegx** [comment]
+1 same problem

**Comment by Sade** [comment]
CSS trick for images

``` CSS
.nyroModalImg { overflow: hidden !important; }
```
